apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-nodeport
  namespace: mongo-express
spec:
  type: NodePort
  selector:
    app: mongoexpress
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30002