apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: mongo-db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: standard
  storageClassName: manual
